/**
 * @module scripts/seats/gen-roster
 *
 * ★★★ 生成「部门花名册」—— 写进 `AGENTS.md`，让**每个 agent 一开场就看见有哪些部门**。
 *
 * ## 为什么是 AGENTS.md（而不是我原先写的判据脚本）
 *
 * 用户 2026-09-27 的裁决（原话）：
 *   > 「直接互相发任务不就好了，你这个机械判有什么依据吗，还不是你这个 LLM 编排的，
 *   >   为什么不让 LLM 自己决定谁发言呢」
 *
 * 这个批评是对的。我原先写的 `route-task.mjs` 里那些关键词（"编排" / "融合"）、
 * 那些权重（+80 / +100）**全是我这个 LLM 拍的** —— 它根本不是"客观判据"，
 * 而是**把我的判断冻成了 if-else**。冻结的代价是它比 LLM 笨（看到"合成"想不到"融合"）。
 *
 * ⇒ 正确做法：**把"谁发言"交给 AI**（它懂语义），**把"有没有乱来"交给门**。
 *   而让 AI 能自己决定的前提是：**它得先知道有哪几个部门、各自管什么**。
 *
 * DSH 已经有现成机制：`@deepseek-ai/dsh-agent-instructions` 会自动把
 * `AGENTS.md` / `CLAUDE.md`（`lib/index.js:19` 逐字）注入每个 agent 的上下文，
 * 且**文件变了会热更新**（"This file changed after it was loaded"）。
 * ⇒ 本模块只负责**生成那份花名册**。
 *
 * ## G0 单一真相源（与 `seat-contract.mjs` 同一条铁律）
 *
 * 花名册的内容**全部来自 `parseSeatContracts()`**（它从 persona 源码解析），
 * **不许手写第二份「谁管什么」** —— 第二份必然与 persona 漂移。
 * ⇒ 本模块**只做渲染**，不做判断。
 *
 * ## 生成物自带指纹（铁律 18：判据要用比名字更强的指纹）
 *
 * 花名册头部写入源码的 **sha256 前 12 位**。于是：
 *   · persona 改了而花名册没重生成 ⇒ `gen-roster.mjs --check` **报红**（可检测漂移）
 *   · 光看"文件存在"是不够的 —— 存在但过期 = 假绿
 */

import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { parseSeatContracts, SEAT_SOURCE } from './seat-contract.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.resolve(HERE, '..', '..')

/** 花名册的输出落点。★ 必须是 AGENTS.md —— 那是 agent-instructions 会自动注入的文件名。 */
export const ROSTER_PATH = path.join(REPO, 'AGENTS.md')

/** 段标记（幂等重写的边界 —— 重写时只替换这一段，不动文件其余内容）。 */
const BEGIN = '<!-- BEGIN:seat-roster (generated by scripts/seats/gen-roster.mjs — DO NOT EDIT BY HAND) -->'
const END = '<!-- END:seat-roster -->'

/** 各席位的 provider 名与工具名（★ 这两项是"接线事实"，不是"职责判断"，
 *  所以它们**必须**与 `packages/subagent-council/src/index.ts` 的
 *  `SEAT_PROVIDER_NAMES` 一致 —— 由 `test-evo-seats-online.mjs` 的 A/B 组把关，此处只引用。 */
const PROVIDER_OF = { architect: 'council-architect', dev: 'evo-dev', review: 'evo-review' }
const TOOLNAME_OF = { architect: 'council_architect', dev: 'evo_dev', review: 'evo_review' }

/** 席位的**显示名**（中文职能名 —— 给人看，不是判据）。 */
const DISPLAY_OF = { architect: '架构师（提方案的人）', dev: '开发脑（动手的人）', review: '审批脑（裁值不值得的人）' }

/** 源码指纹。★ 用**解析所依赖的那个文件**，不是花名册自己。 */
export function sourceFingerprint(sourcePath = SEAT_SOURCE) {
  const bytes = fs.readFileSync(sourcePath)
  return crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 12)
}

/** 每席工具域的说明（★ 与 `SEAT_TOOL_SCOPE` 同源语义；这里只是给人读的话术）。 */
const SEAT_SCOPE_NOTE = {
  architect: '只读（7 个取证工具）—— 它**写不了**文件，所以别派它去改代码',
  dev: '全量（继承父会话）—— 它是**唯一能动手写**的部门',
  review: '只读（7 个取证工具）—— 它**不改**文件，只裁',
}

/**
 * 渲染花名册段落。
 * @param {{contracts?: Record<string, any>, fingerprint?: string}} [opts]
 * @returns {string}
 */
export function renderRoster(opts = {}) {
  const scripts = opts.contracts ?? parseSeatContracts()
  const fp = opts.fingerprint ?? sourceFingerprint()

  const lines = []
  lines.push(BEGIN)
  lines.push('')
  lines.push('## 部门花名册（一人公司：你只与用户对话，具体活交给对口部门）')
  lines.push('')
  lines.push('你可以把任务**直接派给**下列部门。它们各自有固定的职责与人格局限 ——')
  lines.push('**派之前先读它们的「负责」与「不接」两栏**，派错了它们会把活退回来。')
  lines.push('')
  lines.push(`> 本段由 \`scripts/seats/gen-roster.mjs\` 从 \`packages/subagent-council/src/index.ts\` 自动生成。`)
  lines.push(`> 源码指纹 \`${fp}\` —— 若 persona 改了而本段没重生成，\`gen-roster.mjs --check\` 会报红。`)
  lines.push('')

  for (const seat of ['architect', 'dev', 'review']) {
    const c = scripts[seat]
    if (!c) continue
    lines.push(`### ${seat} · ${DISPLAY_OF[seat] ?? seat}`)
    lines.push('')
    lines.push(`- **派活用这个工具**：\`${TOOLNAME_OF[seat] ?? seat}\`（provider \`${PROVIDER_OF[seat] ?? seat}\`）`)
    lines.push(`- **负责**：${c.boundary.admits.join('；') || '(解析不到)'}`)
    if (c.boundary.refuses?.length) {
      lines.push(`- **不接**：${c.boundary.refuses.join('；')}`)
    }
    lines.push(`- **交付形状**（它会被要求按这些段落回答）：${c.sections.join(' / ')}`)
    lines.push(`- **工具域**：${SEAT_SCOPE_NOTE[seat] ?? ''}`)
    lines.push('')
  }

  lines.push('### 派活的纪律')
  lines.push('')
  lines.push('- **派之前**：确认这活属于上面某个「负责」栏。不确定就先问用户，不要硬派。')
  lines.push('- **派之后**：部门是**后台**跑的，你立刻拿到一个 durable subagent id；')
  lines.push('  它跑完会通知你。要给它**追加任务**（不是重开一个）用 `send_message`。')
  lines.push('- **部门之间也能互发**：`send_message` 的目标可以是「你的直属子代理或它下面更深层的代理」')
  lines.push('  （`dsh-tool-subagent-control` 模块注释逐字：*"your direct child or a deeper agent created under you"*）。')
  lines.push('  ⇒ 你**不需要**自己当路由器；把任务的完整上下文交给对口部门，它内部自己转。')
  lines.push('- **不确定时**：`ask_user_question` 是你的正确出口，不是"挑一个最像的派过去"。')
  lines.push('')
  lines.push(END)
  return lines.join('\n')
}

/** 每席工具域的说明（★ 与 `SEAT_TOOL_SCOPE` 同源语义；这里只是给人读的话术）。 */

/**
 * 幂等写入：只替换 `<!-- BEGIN/END -->` 之间，文件其余内容原样保留。
 * @returns {{action:'created'|'replaced'|'appended', path:string, bytes:number}}
 */
export function writeRoster(rosterText, targetPath = ROSTER_PATH) {
  let existing = ''
  try {
    existing = fs.readFileSync(targetPath, 'utf8')
  } catch {
    existing = ''
  }

  let next
  let action
  const bi = existing.indexOf(BEGIN)
  const ei = existing.indexOf(END)
  if (bi >= 0 && ei > bi) {
    next = existing.slice(0, bi) + rosterText + existing.slice(ei + END.length)
    action = 'replaced'
  } else if (existing.trim() === '') {
    next = rosterText + '\n'
    action = 'created'
  } else {
    // 文件已存在但没有本段 ⇒ 追加（**不覆盖用户的其它内容**）
    next = existing.replace(/\s*$/, '') + '\n\n' + rosterText + '\n'
    action = 'appended'
  }

  fs.writeFileSync(targetPath, next, 'utf8')
  return { action, path: targetPath, bytes: Buffer.byteLength(next, 'utf8') }
}

/**
 * ★ 生成器**自己把关**（铁律 40：生成器必须拒绝装坏源、写完复验）。
 *
 * 不做的后果：某次 persona 改坏（解析出空 admits）⇒ 花名册生成一个"负责：(空)"的部门
 * ⇒ 顶层 AI 看到它就会**跳过这个部门**，而没有任何东西报错。
 */
export function selfCheck(rosterText, contracts) {
  const problems = []
  for (const seat of ['architect', 'dev', 'review']) {
    const c = contracts[seat]
    if (!c) { problems.push(`席 ${seat} 解析不到`); continue }
    if (!c.boundary?.admits?.length) problems.push(`席 ${seat} 的 admits 为空`)
    if (!c.sections?.length) problems.push(`席 ${seat} 的段名为空`)
    if (!rosterText.includes(`\`${TOOLNAME_OF[seat]}\``)) problems.push(`花名册里缺 ${seat} 的工具名`)
  }
  // ★ 三席 admits 必须**互不重叠**（否则"派得对"失去依据）
  const all = []
  for (const seat of ['architect', 'dev', 'review']) {
    for (const a of contracts[seat]?.boundary?.admits ?? []) all.push([seat, a])
  }
  for (let i = 0; i < all.length; i++) {
    for (let j = i + 1; j < all.length; j++) {
      if (all[i][0] !== all[j][0] && all[i][1] === all[j][1]) {
        problems.push(`席 ${all[i][0]} 与 ${all[j][0]} 的 admits 重复：「${all[i][1]}」⇒ 路由无区分度`)
      }
    }
  }
  return problems
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────────────────────

const argv = process.argv.slice(2)
/** ★ 只在被直接执行时跑 CLI（被 import 时不动盘 —— 与 `check-import-safe.mjs` 的纪律同族）。 */
const isMain = process.argv[1]?.endsWith('gen-roster.mjs') === true

if (isMain) {
  const checkOnly = argv.includes('--check')
  const contracts = parseSeatContracts()
  const fp = sourceFingerprint()
  const text = renderRoster({ contracts, fingerprint: fp })

  const problems = selfCheck(text, contracts)
  if (problems.length > 0) {
    console.error('[gen-roster] ✗ 自检失败，拒绝写入：')
    for (const p of problems) console.error('  · ' + p)
    process.exit(1)
  }

  if (checkOnly) {
    let onDisk = ''
    try {
      onDisk = fs.readFileSync(ROSTER_PATH, 'utf8')
    } catch { /* 不存在 */ }
    const m = onDisk.match(/源码指纹 `([0-9a-f]{12})`/)
    if (!m) {
      console.error(`[gen-roster] ✗ ${ROSTER_PATH} 里找不到指纹 ⇒ 花名册缺失或未生成`)
      process.exit(1)
    }
    if (m[1] !== fp) {
      console.error(`[gen-roster] ✗ 花名册过期：盘上指纹 ${m[1]}，源码指纹 ${fp} ⇒ 请重跑 gen-roster.mjs`)
      process.exit(1)
    }
    console.log(`[gen-roster] ✓ 花名册与源码同步（指纹 ${fp}）`)
    process.exit(0)
  }

  const r = writeRoster(text)
  // ★ 写完**复验**（不信自己刚写的）
  const written = fs.readFileSync(ROSTER_PATH, 'utf8')
  if (!written.includes('源码指纹 `' + fp + '`')) {
    console.error('[gen-roster] ✗ 写入后复验失败：盘上读不到本次指纹')
    process.exit(1)
  }
  console.log(`[gen-roster] ✓ ${r.action} ${r.path}（${r.bytes} B，指纹 ${fp}）`)
}
